### PR TITLE
Fix #75

### LINKED ISSUE #75: Print a more friendly message when docker desktop not running correctly
### What would you like to change?
If trying to run docker commands when docker desktop is not running, we get an error stack printed to the console when dockerCommon tries to getWslUptimeContainerIP.
I would like a nicer message to be printed, saying there's an issue with connection between wsl and docker desktop and to please restart docker desktop.

### How do you think that would improve the project?
Make it easier for users to understand what has failed and what they can do about it.

### If this entry is related to a bug, please provide the steps to reproduce it
Don't run docker desktop
Try to do any docker commands like docker / ECM setup

### PR DESCRIPTION
**Pull request by Itay-Kirsh**
Improve error message when docker isn't connected correctly.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

File: journeys/et/dockerCommon.ts [hunk 1]
```diff
@@ -47,6 +47,10 @@ async function getDefaultTasks(tasks: TASK_CHOICES) {
 }
 
 export async function configsJourney() {
+  if ((await execCommand('docker info', undefined, false)).stdout.includes("The command 'docker' could not be found")) {
```
Comment (JackReevies) [inline journeys/et/dockerCommon.ts:50]:
```suggestion
 const { stdout } = await execCommand('docker info', undefined, false)
 if (stdout.includes("The command 'docker' could not be found")) {
```

Would prefer splitting out into two lines please. Also, are you sure it comes from stdout and not stderr? I'm aware docker has a dodgy track record of printing progress to stderr and errors to stdout, but have you confirmed this works?

**Review by JackReevies — CHANGES_REQUESTED** [review]

**Review by JackReevies — APPROVED** [review]
